### ISSUE TITLE
Adding new application platform for Smart Home System

### ISSUE THREAD

**Issue by Tahanisk** [Tahanisk/SmartHome#2]
smart home safety system by adding new application platform for users

**Comment by thotaravi95** [comment]
Doing Research on possible applications that can be added into SHS

**Comment by vekariyad** [comment]
can replace it with some other relevant function.

**Comment by vekariyad** [comment]
Doing research on Voice comment control.

**Comment by vekariyad** [comment]
Doing research Voice command control.
